### ISSUE TITLE
3.1.0 - available for Replicape?

### ISSUE THREAD

**Issue by mrRobot62** [intelligent-agent/Refactor#325]
Hi, do you plan, latest refactor-release is available for replicape hardware too?
I would appreciate that :-)

Cheers
Bernd

**Comment by goeland86** [comment]
Hi Bernd,

No we're not. The latest developments are primarily klipper enhancements
for recore support, where the replicape has full mainline support already.

If you know of bugs on replicape that we can fix, we're happy to address
them and create new bugfix releases for it though.

Jon

**Comment by mrRobot62** [comment]
ok - Jon - thanks for response. Will come back with issues.

BTW:
Today I ruined my eMMC :-O - tried to put SDCard into fstab - now System do not reboot anymore from eMMC :-O 

Any suggestions - without refreshing and reconfiguring everything?

**Comment by eliasbakken** [comment]
There are images for BeagleBone you can use that do not automatically flash the eMMC. You can use that to boot the board and then mount the eMMC and edit the fstab file from there.

**Comment by ibitbang** [comment]
@goeland86 sorry to raise a dead issue, but would the latest image work on BeagleBone Black + replicape? 
Or have they diverged and I need to use the v3.0.3 version?

**Comment by goeland86** [comment]
At this point I think they have diverged too much. Recore is using rebuild now, not refactor. And because of the specific requirements for the kernel needed for replicape, I'm not even sure we could build a new image that works today. There's been so many changes in so many places... The board is over a decade old now. The BBB has limited memory and the new features eat that quickly.
