### ISSUE TITLE
Running grep on root with a USB drive inserted causes a panic

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#364]
Running `grep -r "test-test" /` for instance causes a complete freeze.

**Comment by eliasbakken** [comment]
It seems having the USB drive with Refactor installed causes some instability and seems to also cause a freeze during booting. It might be related to the double mounting in /etc/fstab

**Comment by goeland86** [comment]
Hmm. In that case we should really be doing a uuid based fstab, and use a
command street dd to change the uuid of the emmc partitions.
Or the other way around, changing the USB drive's.

**Comment by eliasbakken** [comment]
I'm getting an error message ```musb-sunxi 1c19000.usb: Error unknown readw offset 0``` and repeated several times before the freeze.

**Comment by eliasbakken** [comment]
Upgrading to kernel 6.1 and running `cat /sys/kernel/debug/usb/musb-hdrc.4.auto/regdump` produces the `Error unknown readw offset` issue. 
It seems that doing anything with `/sys/kernel/debug/psci` can also lead to a crash.

**Comment by goeland86** [comment]
Uh... The values in the debug may need to be read by special utils or when
the kernel is booted with debug arguments?

Otherwise, yeah, i can see you could cause crashes with that, especially if
you're trying to access values that are otherwise restricted because of
security features that are enabled by default?
