### ISSUE TITLE
NetworkManager does not manage USB eth interfaces

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#70]
For consistency reasons, it is best to have the NetworkManager also take care of setting up the USB-ethernet interfaces, instead of having them managed by extraneous scripts.

**Comment by eliasbakken** [comment]
USB seems to be managed by NetworkManager, so that is no longer a problem it seems. There are some issues with connecting and disconnecting the USB, in that Ethernet does not immediately get a new IP and Avahi seems to get confused by having mulitiple interfaces, but this seems like a different problem, so I will close this issue for now.
